### ISSUE TITLE
how to get static built executable

### ISSUE THREAD

**Issue by cyberyoung** [aheit/cantools#3]
I use
```
./configure --enable-static --enable-static-exec CFLAGS="-std=c99 -static -static-libgcc -static-libstdc++ -static-libasan -static-libtsan"
```
but get
```
 file cantools-install/bin/*
cantools-install/bin/asctomat:      symbolic link to `cantomat'
cantools-install/bin/blftomat:      symbolic link to `cantomat'
cantools-install/bin/cantomat:      ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.32, BuildID[sha1]=0e71e0d7ea233fac19f2e2bc9b45e048e08b9249, not stripped
cantools-install/bin/clgtomat:      symbolic link to `cantomat'
```

Any help will be appreciated. Thanks.

**Comment by aheit** [comment]
Hello Yang,

thanks for your question. I will look into it. Give me some time.

 If you figure it out yourself in the meantime, let me know. I would like
to add the solution to the documentation.

Regards,
Andreas

Am 27.10.2017 05:12 schrieb "Yang Li" <notifications@github.com>:

I use

./configure --enable-static --enable-static-exec CFLAGS="-std=c99
-static -static-libgcc -static-libstdc++ -static-libasan
-static-libtsan"

but get

 file cantools-install/bin/*
cantools-install/bin/asctomat:      symbolic link to `cantomat'
cantools-install/bin/blftomat:      symbolic link to `cantomat'
cantools-install/bin/cantomat:      ELF 64-bit LSB executable, x86-64,
version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux
2.6.32, BuildID[sha1]=0e71e0d7ea233fac19f2e2bc9b45e048e08b9249, not
stripped
cantools-install/bin/clgtomat:      symbolic link to `cantomat'

Any help will be appreciated. Thanks.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/aheit/cantools/issues/3>, or mute the thread

**Comment by cyberyoung** [comment]
@aheit we succeeded with using gcc manually after make
```/bin/sh ./libtool  --tag=CC   --mode=link gcc  -std=c99 -static   -o cantomat src/cantomat/cantomat-cantomat.o src/cantomat/cantomat-messagedecoder.o src/cantomat/cantomat-busassignment.o src/cantomat/cantomat-matwrite.o src/cantomat/cantomat-messagehash.o src/cantomat/cantomat-measurement.o src/cantomat/cantomat-signalformat.o src/hashtable/cantomat-hashtable.o src/hashtable/cantomat-hashtable_itr.o libcandbc.la libcanasc.la libcanblf.la libcanvsb.la libcanclg.la -lmatio -lhdf5 -lz   -lz    -lm -lz -all-static```
