### ISSUE TITLE
mdftomat bug in sorted mdf file

### ISSUE THREAD

**Issue by zhuimengqq** [aheit/cantools#7]
I found that for the sorted mdf file, the converted result mat file, the first column is the same number.

when  mdf file is not sorted, the converted result is right.

**Comment by aheit** [comment]
Hello Zhuimengqq,

thank you for your report. Can you provide me a sorted mdf file which shows the issue?

Regards,
Andreas

**Comment by zhuimengqq** [comment]
Hi:
  aheit,Thanks for you Reply,Thank you very much for your help.this is the sorted  mdf file.
[date.zip](https://github.com/aheit/cantools/files/3220495/date.zip)

**Comment by aheit** [comment]
Hello zhuimengqq,

thank you for preparing the files and sorry for the late reply.

With the help of your data, I located the problem in the function
mdfProcessChannelsSorted. In current version, the time data is not usable,
because it is not initialized correctly. I don't have an immediate solution
and I need a bit more time to think about it. I'll let you know when I have
a fix.

Regards,
Andreas





Am So., 26. Mai 2019 um 17:52 Uhr schrieb zhuimengqq <
notifications@github.com>:

**Comment by aheit** [comment]
Hello zhuimengqq, I updated the repository with a fix that corrected the issue for me. Please check if it works for you.

**Comment by zhuimengqq** [comment]
Hello  aheit, thanks for you  continuous improvement of  cantools.
I test ,the bug is fixed.I tried to compile it to windows using cygwin. It succeeded and work fine. 
it is:
https://github.com/zhuimengqq/cantools/files/3315130/cantools-release-0.25.for.windows.zip
